version: '3'

networks:
  services-net:
    driver: bridge

volumes:
  db:
    driver: local

services:

  nginx: #reverse proxy
    image: nginx
    container_name: reverse_proxy
    restart: always
    hostname: 'nginx'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # ro - read only
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf:ro
      - ./nginx/ssl/localhost.crt:/etc/ssl/certs/localhost.crt:ro
      - ./nginx/ssl/localhost.key:/etc/ssl/certs/localhost.key:ro
      - ./nginx/logs/:/var/log/nginx/
    ports:
      - '80:80'
      - '443:443'
  
  database:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file:
      - src/Scripts/database/database.env # configure postgres
    networks:
      - services-net
    volumes:
      - src\Scripts\database:/docker-entrypoint-initdb.d/ # inital queries / commands
      - database-data:/var/lib/postgresql/data/ # persist data

#  rabbitmq: #event bus
#    image: rabbitmq:3-management-alpine
#    container_name: event_bus
#    restart: unless-stopped
#    ports:
#        - "5672:5672"
#        - "15672:15672"
#    networks:
#      - services-net
#    
#  redis:
#    image: redis:alpine
#    container_name: redis
#    ports:
#      - "6379:6379"
#    networks:
#      - services-net
#    restart: always

######### SERVICES ###########
    
  identity_service:
    build: src/services/IdentityService/
    container_name: identity_service
    ports:
      - "8001:8001"
    networks:
      - services-net
    depends_on:
      - nginx
      - database
      - rabbitmq
      - redis

  catalog_service:
    build: src/services/CatalogService/
    container_name: catalog_service
    ports:
      - "8002:8002"
    networks:
      - services-net
    depends_on:
      - identity_service
  
  ordering_service:
    build: src/services/OrderingService/
    container_name: ordering_service
    ports:
      - "8003:8003"
    networks:
      - services-net
    depends_on:
      - identity_service
    